
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'versai'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/u358688394/domains/newyeardhamaka.in/public_html'
    readyTimeout: '20000'
